Type: AWS::IAM::Role
Properties:
  Path: /
  RoleName: listCats-${self:custom.stage}-${self:custom.region}-lambdaRole
  AssumeRolePolicyDocument: ${file(security/permissions/assumeRole.yml)}
  Policies:
    - PolicyName: listCats-${self:custom.stage}-${self:custom.region}-Policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - ${file(security/permissions/logging.yml)}
          