service: cat-api

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev${env:USER, env:USERNAME}
  region: eu-west-2
  environment:
    STAGE: ${self:custom.stage}
    DEBUG_LOGGING_IS_ENABLED: ${self:custom.variables.debugLoggingIsEnabled}

plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-bind-deployment-id

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  defaultVariables: dev-user
  variables: ${file(./variables.yml):${opt:stage, self:custom.defaultVariables}}

functions:
  # Responses are not cached
  list-all-cats:
    handler: rest_api/cats/get/handler.handle
    role: listCatsRole
    events:
      - http:
          path: /cats
          method: get
     
  # Responses are cached based the 'pawId' path parameter and the 'Accept-Language' header
  get-cat-by-paw-id:
    handler: rest_api/cat/get/handler.handle
    role: getCatRole
    events:
      - http:
          path: /cats/{pawId}
          method: get
    
resources:
  Resources:
    __deployment__:
      Properties:
        Description: Deploying the Cat API. Meow.
    ApiGatewayStage:
      Type: "AWS::ApiGateway::Stage"
      Properties:
        CacheClusterEnabled: ${self:custom.variables.cachingIsEnabled}
        CacheClusterSize: 0.5
        MethodSettings:
          - ResourcePath: "/*"
            HttpMethod: "*"
            CachingEnabled: false
        RestApiId:
          Ref: ApiGatewayRestApi
        DeploymentId:
          Ref: __deployment__
        StageName: ${self:custom.stage}
    ApiGatewayMethodCatsPawidVarGet:
      Properties:
        HttpMethod: GET
        #CacheTtlInSeconds: 3600 <-- this is not a valid field; I assume you can set a TTL per endpoint though?
        RequestParameters:
          method.request.path.pawId: true
          method.request.header.Accept-Language: true
        Integration:
          RequestParameters:
            integration.request.path.pawId: method.request.path.pawId
            integration.request.header.Accept-Language: method.request.header.Accept-Language
          CacheNamespace: ApiGatewayMethodCatsPawidVarGetCacheNS
          CacheKeyParameters:
            - method.request.path.pawId
            - method.request.header.Accept-Language
    listCatsRole: ${file(security/roles/listCatsRole.yml)}
    getCatRole: ${file(security/roles/getCatRole.yml)}
